// Package shim generates per-package-manager interception shim scripts.
package shim

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// PackageManagers is the list of supported PMs per PRD D-02.
var PackageManagers = []string{
	"npm", "yarn", "pnpm",
	"pip", "pip3", "uv", "poetry",
	"cargo",
	"gem", "bundler",
	"go",
	"dotnet",
	"conda",
	// NuGet excluded pending OQ-EP-V4-03 audit
}

// shimTemplate generates a bash shim that:
//  1. Locates the real PM binary by walking PATH and skipping the shim directory.
//  2. Performs an HTTP identity handshake against the proxy's health endpoint.
//     A bare open port is NOT trusted — the response must contain the Phoenix
//     identity marker (prevents routing through an unrelated process on the port).
//  3. If verified: exports HTTPS_PROXY + HTTP_PROXY + PM-specific CA env vars.
//  4. If unverified + fail-open (default): runs the real PM unscanned.
//  5. If unverified + fail-closed: prints why and exits 1.
const shimTemplate = `#!/usr/bin/env bash
# Phoenix Security Blue Shield - Firewall — {{.PM}} shim
# Generated by phoenix-firewall init. DO NOT EDIT manually.

# Bypass: only skip interception if the firewall API authorizes this token.
# 'bypass verify' is server-anchored and fails closed, so an unauthorized or
# unverifiable token falls through to normal (proxied) execution below.
if [ -n "${PHOENIX_FIREWALL_BYPASS_TOKEN:-}" ]; then
    if command -v phoenix-firewall >/dev/null 2>&1 && phoenix-firewall bypass verify >/dev/null 2>&1; then
        _SHIM_DIR="${HOME}/.local/bin"
        IFS=: read -ra _DIRS <<< "$PATH"
        for _d in "${_DIRS[@]}"; do
            [ "$_d" = "$_SHIM_DIR" ] && continue
            if [ -x "${_d}/{{.PM}}" ]; then
                exec "${_d}/{{.PM}}" "$@"
            fi
        done
        echo "[phoenix-firewall] cannot find real {{.PM}} in PATH" >&2; exit 127
    fi
    echo "[phoenix-firewall] bypass token not authorized — routing through firewall" >&2
fi

# Locate real {{.PM}} binary, skipping our shim directory
_SHIM_DIR="${HOME}/.local/bin"
_REAL=""
IFS=: read -ra _DIRS <<< "$PATH"
for _d in "${_DIRS[@]}"; do
    [ "$_d" = "$_SHIM_DIR" ] && continue
    if [ -x "${_d}/{{.PM}}" ]; then
        _REAL="${_d}/{{.PM}}"
        break
    fi
done

if [ -z "$_REAL" ]; then
    echo "[phoenix-firewall] cannot find real {{.PM}} (shim dir excluded from search)" >&2
    exit 127
fi

# Identity handshake: confirm the listener on the proxy port is really the Phoenix
# firewall (not some other process bound to {{.ProxyPort}}). Pure bash, no curl.
# NOTE: use { exec ...; } 2>/dev/null so the 2>/dev/null is scoped to the block,
# not applied permanently to the shell's stderr. A bare exec with redirections
# permanently alters fd 2, silencing all subsequent messages.
_PHOENIX_VERIFIED=1   # 0 = verified Phoenix proxy
_PHOENIX_PORT_OPEN=1  # 0 = something is listening
{ exec 3<>/dev/tcp/127.0.0.1/{{.ProxyPort}}; } 2>/dev/null
if [ $? -eq 0 ]; then
    _PHOENIX_PORT_OPEN=0
    if printf 'GET /__phoenix/health HTTP/1.0\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n' >&3 2>/dev/null; then
        while IFS= read -r -t 2 _line <&3 2>/dev/null; do
            case "$_line" in
                *'"service":"phoenix-firewall"'*) _PHOENIX_VERIFIED=0; break ;;
            esac
        done
    fi
    { exec 3>&-; } 2>/dev/null
fi

_PHOENIX_FAIL_MODE="${PHOENIX_FAIL_MODE:-{{.FailMode}}}"

if [ "$_PHOENIX_VERIFIED" = "0" ]; then
    _CA="${HOME}/.config/phoenix-firewall/phoenix-ca.crt"
    export HTTPS_PROXY="http://127.0.0.1:{{.ProxyPort}}"
    export HTTP_PROXY="http://127.0.0.1:{{.ProxyPort}}"
{{.CAExports}}    [ -n "${PHOENIX_FIREWALL_VERBOSE:-}" ] && echo "[phoenix-firewall] proxy verified — {{.PM}} traffic will be scanned" >&2
else
    if [ "$_PHOENIX_PORT_OPEN" = "0" ]; then
        echo "[phoenix-firewall] warning: a process is listening on 127.0.0.1:{{.ProxyPort}} but it is not the Phoenix firewall proxy (identity handshake failed); not routing {{.PM}} through it" >&2
    fi
    if [ "$_PHOENIX_FAIL_MODE" = "closed" ]; then
        echo "[phoenix-firewall] {{.PM}} blocked: firewall proxy unavailable and fail_mode=closed" >&2
        echo "[phoenix-firewall] start it with 'phoenix-firewall proxy', or set PHOENIX_FAIL_MODE=open to override" >&2
        exit 1
    fi
    [ -n "${PHOENIX_FIREWALL_VERBOSE:-}" ] && echo "[phoenix-firewall] firewall proxy not reachable — proceeding without scanning (fail_mode=open)" >&2
fi

exec "$_REAL" "$@"
`

// Generator writes shim scripts to the given directory.
type Generator struct {
	OutputDir string
	ProxyPort int    // defaults to 8080
	FailMode  string // "open" (default) or "closed"
}

type shimData struct {
	PM        string
	Ecosystem string
	ProxyPort int
	CAExports string // pre-rendered bash export lines
	FailMode  string
}

func (g *Generator) Generate() error {
	port := g.ProxyPort
	if port == 0 {
		port = 8080
	}
	failMode := g.FailMode
	if failMode != "closed" {
		failMode = "open"
	}
	tmpl, err := template.New("shim").Parse(shimTemplate)
	if err != nil {
		return fmt.Errorf("shim template parse: %w", err)
	}
	for _, pm := range PackageManagers {
		path := filepath.Join(g.OutputDir, pm)
		f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
		if err != nil {
			return fmt.Errorf("open shim %s: %w", pm, err)
		}
		data := shimData{
			PM:        pm,
			Ecosystem: ecosystemOf(pm),
			ProxyPort: port,
			CAExports: caExportsOf(pm),
			FailMode:  failMode,
		}
		if err := tmpl.Execute(f, data); err != nil {
			f.Close()
			return fmt.Errorf("write shim %s: %w", pm, err)
		}
		f.Close()
	}
	return nil
}

// caExportsOf returns pre-rendered bash export lines for the PM-specific CA env vars,
// each indented with 4 spaces and terminated with a newline.
func caExportsOf(pm string) string {
	vars := caEnvVarsOf(pm)
	if len(vars) == 0 {
		return ""
	}
	var sb strings.Builder
	for _, v := range vars {
		sb.WriteString(`    export `)
		sb.WriteString(v)
		sb.WriteString(`="${_CA}"`)
		sb.WriteByte('\n')
	}
	return sb.String()
}

// caEnvVarsOf returns the env var names that a PM uses to locate a custom CA bundle.
// Go is intentionally absent — it uses the system trust store with no override env var.
func caEnvVarsOf(pm string) []string {
	m := map[string][]string{
		"npm":     {"NODE_EXTRA_CA_CERTS"},
		"yarn":    {"NODE_EXTRA_CA_CERTS"},
		"pnpm":    {"NODE_EXTRA_CA_CERTS"},
		"pip":     {"PIP_CERT", "REQUESTS_CA_BUNDLE"},
		"pip3":    {"PIP_CERT", "REQUESTS_CA_BUNDLE"},
		"uv":      {"SSL_CERT_FILE"},
		"poetry":  {"REQUESTS_CA_BUNDLE"},
		"cargo":   {"CARGO_HTTP_CAINFO"},
		"gem":     {"SSL_CERT_FILE"},
		"bundler": {"BUNDLE_SSL_CA_CERT"},
		"dotnet":  {"SSL_CERT_FILE"},
		"conda":   {"SSL_CERT_FILE"},
	}
	if vars, ok := m[pm]; ok {
		return vars
	}
	return nil
}

func ecosystemOf(pm string) string {
	m := map[string]string{
		"npm": "npm", "yarn": "npm", "pnpm": "npm",
		"pip": "pypi", "pip3": "pypi", "uv": "pypi", "poetry": "pypi",
		"cargo": "crates.io",
		"gem":   "rubygems", "bundler": "rubygems",
		"go":     "go",
		"dotnet": "nuget",
		"conda":  "conda",
	}
	if eco, ok := m[pm]; ok {
		return eco
	}
	return pm
}
