// Package shim generates per-package-manager interception shim scripts.
package shim

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// PackageManagers is the list of supported PMs per PRD D-02.
var PackageManagers = []string{
	"npm", "yarn", "pnpm",
	"pip", "pip3", "uv", "poetry",
	"cargo",
	"gem", "bundler",
	"go",
	"dotnet",
	"conda",
	// NuGet excluded pending OQ-EP-V4-03 audit
}

const shimTemplate = `#!/usr/bin/env bash
# Phoenix Supply Chain Firewall — {{.PM}} shim
# Generated by phoenix-firewall init. DO NOT EDIT manually.
set -euo pipefail
if [ -n "${PHOENIX_FIREWALL_BYPASS_TOKEN:-}" ]; then
    exec "$(command -v {{.PM}} 2>/dev/null || echo /usr/local/bin/{{.PM}}.real)" "$@"
fi
exec phoenix-firewall agent-bridge --ecosystem {{.Ecosystem}} --command "{{.PM}} $*" -- "$(command -v {{.PM}}.real || true)" "$@"
`

// Generator writes shim scripts to the given directory.
type Generator struct {
	OutputDir string
}

func (g *Generator) Generate() error {
	tmpl, err := template.New("shim").Parse(shimTemplate)
	if err != nil {
		return fmt.Errorf("shim template parse: %w", err)
	}
	for _, pm := range PackageManagers {
		path := filepath.Join(g.OutputDir, pm)
		f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
		if err != nil {
			return fmt.Errorf("open shim %s: %w", pm, err)
		}
		data := struct{ PM, Ecosystem string }{PM: pm, Ecosystem: ecosystemOf(pm)}
		if err := tmpl.Execute(f, data); err != nil {
			f.Close()
			return fmt.Errorf("write shim %s: %w", pm, err)
		}
		f.Close()
	}
	return nil
}

func ecosystemOf(pm string) string {
	m := map[string]string{
		"npm": "npm", "yarn": "npm", "pnpm": "npm",
		"pip": "pypi", "pip3": "pypi", "uv": "pypi", "poetry": "pypi",
		"cargo": "crates.io",
		"gem": "rubygems", "bundler": "rubygems",
		"go": "go",
		"dotnet": "nuget",
		"conda": "conda",
	}
	if eco, ok := m[pm]; ok {
		return eco
	}
	return pm
}
