//go:build windows
// +build windows

package shim

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func UserShimDir() string {
	appData := os.Getenv("APPDATA")
	if appData == "" {
		home, _ := os.UserHomeDir()
		appData = filepath.Join(home, "AppData", "Roaming")
	}
	return filepath.Join(appData, "PhoenixFirewall", "shims")
}

// cmdShimTemplate is a Windows batch shim that mirrors the bash shim logic:
//  1. Skips bypass-token path.
//  2. Finds the real PM binary via where.exe, excluding the shim directory.
//  3. Probes 127.0.0.1:8080 via PowerShell; if up, sets HTTPS_PROXY, HTTP_PROXY,
//     and PM-specific CA env vars before executing the real PM.
//  4. If proxy is down, fails-open (default) or fails-closed (PHOENIX_FAIL_MODE=closed).
// NOTE: Windows shim uses a bare TCP probe (no HTTP identity handshake) — this is a
// known gap relative to the bash shim. Full handshake requires PowerShell 5+ WebClient;
// tracked for a follow-up PR.
const cmdShimTemplate = `@echo off
REM Phoenix Security Blue Shield - Firewall — %s shim
REM Generated by phoenix-firewall init. DO NOT EDIT manually.

setlocal enabledelayedexpansion

%s
REM Apply baked-in fail_mode default; runtime PHOENIX_FAIL_MODE overrides.
if not defined PHOENIX_FAIL_MODE set "PHOENIX_FAIL_MODE=%s"

REM Bypass: only skip interception if the firewall API authorizes this token.
REM 'bypass verify' is server-anchored and fails closed; an unauthorized or
REM unverifiable token falls through to normal (proxied) execution below.

if defined PHOENIX_FIREWALL_BYPASS_TOKEN (
    phoenix-firewall bypass verify >nul 2>&1
    if errorlevel 1 (
        echo [phoenix-firewall] bypass token not authorized - routing through firewall >&2
    ) else (
        for /f "delims=" %%%%i in ('where %s 2^>nul') do (
            if /i not "%%%%~dpi"=="%s\" (
                "%%%%i" %%*
                exit /b %%ERRORLEVEL%%
            )
        )
        echo %s: command not found >&2 & echo [phoenix-firewall] note: no real %s on PATH; nothing to run ^(firewall shim is pass-through only^) >&2 & exit /b 127
    )
)

set _REAL=
for /f "delims=" %%%%i in ('where %s 2^>nul') do (
    if /i not "%%%%~dpi"=="%s\" (
        if not defined _REAL set "_REAL=%%%%i"
    )
)
if not defined _REAL (
    echo %s: command not found >&2 & echo [phoenix-firewall] note: no real %s on PATH; nothing to run ^(firewall shim is pass-through only^) >&2 & exit /b 127
)

set _PROXY_UP=0
powershell -nologo -noprofile -command "try{$t=New-Object Net.Sockets.TcpClient;$t.Connect('127.0.0.1',%s);$t.Close();exit 0}catch{exit 1}" >nul 2>&1
if %%ERRORLEVEL%% EQU 0 set _PROXY_UP=1

if "%%_PROXY_UP%%"=="1" (
    set "HTTPS_PROXY=http://127.0.0.1:%s"
    set "HTTP_PROXY=http://127.0.0.1:%s"
%s) else if /i "%%PHOENIX_FAIL_MODE%%"=="closed" (
    echo [phoenix-firewall] proxy unavailable - %s blocked (PHOENIX_FAIL_MODE=closed) >&2
    exit /b 1
) else (
    REM This install is about to run WITHOUT firewall evaluation (fail_mode=open).
    REM Always record it so the endpoint daemon's heartbeat can surface it.
    if not exist "%%USERPROFILE%%\.config\phoenix-firewall" mkdir "%%USERPROFILE%%\.config\phoenix-firewall" >nul 2>&1
    echo %%DATE%% %%TIME%%	%s	unverified_proxy_fail_open>>"%%USERPROFILE%%\.config\phoenix-firewall\bypass.log" 2>nul
)

"%%_REAL%%" %%*
exit /b %%ERRORLEVEL%%
`

// InstallPATH installs batch shims to %APPDATA%\PhoenixFirewall\shims.
// failMode is baked into each shim as the default for PHOENIX_FAIL_MODE.
// proxyPort is the local port the phoenix-firewall proxy listens on (default 8080).
// denyScripts forces npm/pnpm lifecycle scripts off regardless of firewall verdict.
func InstallPATH(failMode string, proxyPort int, denyScripts bool) error {
	fm := failMode
	if fm != "closed" {
		fm = "open"
	}
	port := proxyPort
	if port == 0 {
		port = 8080
	}
	shimDir := UserShimDir()
	if err := os.MkdirAll(shimDir, 0755); err != nil {
		return fmt.Errorf("create shim dir: %w", err)
	}
	shimDirBackslash := shimDir + `\`
	portStr := fmt.Sprintf("%d", port)

	for _, pm := range PackageManagers {
		caExports := windowsCAExportsOf(pm)
		var denyScriptsExports string
		if denyScripts {
			denyScriptsExports = windowsDenyScriptsExportsOf(pm)
		}
		content := fmt.Sprintf(cmdShimTemplate,
			pm,                 // REM header
			denyScriptsExports, // unconditional lifecycle-script deny (test mode)
			fm,                 // baked-in PHOENIX_FAIL_MODE default
			pm,                 // where (bypass)
			shimDirBackslash,   // exclusion (bypass)
			pm,                 // echo (bypass): "%s: command not found"
			pm,                 // echo (bypass): "no real %s on PATH"
			pm,                 // where (main)
			shimDirBackslash,   // exclusion (main)
			pm,                 // echo (not found): "%s: command not found"
			pm,                 // echo (not found): "no real %s on PATH"
			portStr,            // PowerShell TCP probe port
			portStr,            // HTTPS_PROXY port
			portStr,            // HTTP_PROXY port
			caExports,          // CA env var lines
			pm,                 // echo (fail-closed)
			pm,                 // bypass.log entry (fail-open)
		)
		path := filepath.Join(shimDir, pm+".cmd")
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("write shim %s: %w", pm, err)
		}
	}
	fmt.Printf("[phoenix-firewall] shims installed to %s\n", shimDir)
	fmt.Printf("[phoenix-firewall] add %s to your PATH via System Properties > Environment Variables\n", shimDir)
	return nil
}

// windowsDenyScriptsExportsOf returns a batch SET line that disables lifecycle
// scripts for the given PM, or "" if the PM has no reliable env-var mechanism
// (see denyScriptsEnvVarOf).
func windowsDenyScriptsExportsOf(pm string) string {
	v := denyScriptsEnvVarOf(pm)
	if v == "" {
		return ""
	}
	return fmt.Sprintf("set \"%s=true\"\n", v)
}

// windowsCAExportsOf returns pre-rendered batch SET lines for PM-specific CA env vars.
func windowsCAExportsOf(pm string) string {
	caPath := `%USERPROFILE%\.config\phoenix-firewall\phoenix-ca.crt`
	vars := caEnvVarsOf(pm)
	if len(vars) == 0 {
		return ""
	}
	var sb strings.Builder
	for _, v := range vars {
		sb.WriteString(`    set "`)
		sb.WriteString(v)
		sb.WriteString(`=`)
		sb.WriteString(caPath)
		sb.WriteString(`"`)
		sb.WriteByte('\n')
	}
	return sb.String()
}

func UninstallPATH() error {
	shimDir := UserShimDir()
	for _, pm := range PackageManagers {
		_ = os.Remove(filepath.Join(shimDir, pm+".cmd"))
	}
	return nil
}
