//go:build windows
// +build windows

package shim

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func UserShimDir() string {
	appData := os.Getenv("APPDATA")
	if appData == "" {
		home, _ := os.UserHomeDir()
		appData = filepath.Join(home, "AppData", "Roaming")
	}
	return filepath.Join(appData, "PhoenixFirewall", "shims")
}

// cmdShimTemplate is a Windows batch shim that mirrors the bash shim logic:
//  1. Skips bypass-token path.
//  2. Finds the real PM binary via where.exe, excluding the shim directory.
//  3. Probes 127.0.0.1:8080 via PowerShell; if up, sets HTTPS_PROXY, HTTP_PROXY,
//     and PM-specific CA env vars before executing the real PM.
//  4. If proxy is down, fails-open (default) or fails-closed (PHOENIX_FAIL_MODE=closed).
// NOTE: Windows shim uses a bare TCP probe (no HTTP identity handshake) — this is a
// known gap relative to the bash shim. Full handshake requires PowerShell 5+ WebClient;
// tracked for a follow-up PR.
const cmdShimTemplate = `@echo off
REM Phoenix Security Blue Shield - Firewall — %s shim
REM Generated by phoenix-firewall init. DO NOT EDIT manually.

setlocal enabledelayedexpansion

REM Apply baked-in fail_mode default; runtime PHOENIX_FAIL_MODE overrides.
if not defined PHOENIX_FAIL_MODE set "PHOENIX_FAIL_MODE=%s"

if defined PHOENIX_FIREWALL_BYPASS_TOKEN (
    for /f "delims=" %%%%i in ('where %s 2^>nul') do (
        if /i not "%%%%~dpi"=="%s\" (
            "%%%%i" %%*
            exit /b %%ERRORLEVEL%%
        )
    )
    echo [phoenix-firewall] cannot find real %s >&2 & exit /b 127
)

set _REAL=
for /f "delims=" %%%%i in ('where %s 2^>nul') do (
    if /i not "%%%%~dpi"=="%s\" (
        if not defined _REAL set "_REAL=%%%%i"
    )
)
if not defined _REAL (
    echo [phoenix-firewall] cannot find real %s in PATH >&2 & exit /b 127
)

set _PROXY_UP=0
powershell -nologo -noprofile -command "try{$t=New-Object Net.Sockets.TcpClient;$t.Connect('127.0.0.1',8080);$t.Close();exit 0}catch{exit 1}" >nul 2>&1
if %%ERRORLEVEL%% EQU 0 set _PROXY_UP=1

if "%%_PROXY_UP%%"=="1" (
    set "HTTPS_PROXY=http://127.0.0.1:8080"
    set "HTTP_PROXY=http://127.0.0.1:8080"
%s) else if /i "%%PHOENIX_FAIL_MODE%%"=="closed" (
    echo [phoenix-firewall] proxy unavailable - %s blocked (PHOENIX_FAIL_MODE=closed) >&2
    exit /b 1
)

"%%_REAL%%" %%*
exit /b %%ERRORLEVEL%%
`

// InstallPATH installs batch shims to %APPDATA%\PhoenixFirewall\shims.
// failMode is baked into each shim as the default for PHOENIX_FAIL_MODE.
func InstallPATH(failMode string) error {
	fm := failMode
	if fm != "closed" {
		fm = "open"
	}
	shimDir := UserShimDir()
	if err := os.MkdirAll(shimDir, 0755); err != nil {
		return fmt.Errorf("create shim dir: %w", err)
	}
	shimDirBackslash := shimDir + `\`

	for _, pm := range PackageManagers {
		caExports := windowsCAExportsOf(pm)
		content := fmt.Sprintf(cmdShimTemplate,
			pm,               // REM header
			fm,               // baked-in PHOENIX_FAIL_MODE default
			pm,               // where (bypass)
			shimDirBackslash, // exclusion (bypass)
			pm,               // echo (bypass)
			pm,               // where (main)
			shimDirBackslash, // exclusion (main)
			pm,               // echo (not found)
			caExports,        // CA env var lines
			pm,               // echo (fail-closed)
		)
		path := filepath.Join(shimDir, pm+".cmd")
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("write shim %s: %w", pm, err)
		}
	}
	fmt.Printf("[phoenix-firewall] shims installed to %s\n", shimDir)
	fmt.Printf("[phoenix-firewall] add %s to your PATH via System Properties > Environment Variables\n", shimDir)
	return nil
}

// windowsCAExportsOf returns pre-rendered batch SET lines for PM-specific CA env vars.
func windowsCAExportsOf(pm string) string {
	caPath := `%USERPROFILE%\.config\phoenix-firewall\phoenix-ca.crt`
	vars := caEnvVarsOf(pm)
	if len(vars) == 0 {
		return ""
	}
	var sb strings.Builder
	for _, v := range vars {
		sb.WriteString(`    set "`)
		sb.WriteString(v)
		sb.WriteString(`=`)
		sb.WriteString(caPath)
		sb.WriteString(`"`)
		sb.WriteByte('\n')
	}
	return sb.String()
}

func UninstallPATH() error {
	shimDir := UserShimDir()
	for _, pm := range PackageManagers {
		_ = os.Remove(filepath.Join(shimDir, pm+".cmd"))
	}
	return nil
}
