package bypass

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
)

const keyFileName = "bypass-signing-key.pem"
const pubKeyFileName = "bypass-signing-key.pub.pem"

// KeyPaths returns the private and public key paths under cfgDir.
func KeyPaths(cfgDir string) (privPath, pubPath string) {
	return filepath.Join(cfgDir, keyFileName), filepath.Join(cfgDir, pubKeyFileName)
}

// EnsureKeyPair generates an ED25519 keypair in cfgDir if one doesn't exist.
// Returns (privateKey, publicKey, error).
func EnsureKeyPair(cfgDir string) (ed25519.PrivateKey, ed25519.PublicKey, error) {
	privPath, pubPath := KeyPaths(cfgDir)
	if _, err := os.Stat(privPath); err == nil {
		return LoadKeyPair(privPath, pubPath)
	}
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, nil, fmt.Errorf("generate key: %w", err)
	}
	if err := savePrivKey(privPath, priv); err != nil {
		return nil, nil, err
	}
	if err := savePubKey(pubPath, pub); err != nil {
		return nil, nil, err
	}
	fmt.Printf("[phoenix-firewall] generated bypass signing key: %s\n", privPath)
	return priv, pub, nil
}

// LoadKeyPair loads an existing ED25519 keypair from PEM files.
func LoadKeyPair(privPath, pubPath string) (ed25519.PrivateKey, ed25519.PublicKey, error) {
	privPEM, err := os.ReadFile(privPath)
	if err != nil {
		return nil, nil, fmt.Errorf("read priv key: %w", err)
	}
	block, _ := pem.Decode(privPEM)
	if block == nil {
		return nil, nil, fmt.Errorf("invalid PEM: %s", privPath)
	}
	priv, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, nil, fmt.Errorf("parse priv key: %w", err)
	}
	ed, ok := priv.(ed25519.PrivateKey)
	if !ok {
		return nil, nil, fmt.Errorf("not an ED25519 key")
	}
	return ed, ed.Public().(ed25519.PublicKey), nil
}

func savePrivKey(path string, priv ed25519.PrivateKey) error {
	b, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		return err
	}
	return os.WriteFile(path, pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: b}), 0600)
}

func savePubKey(path string, pub ed25519.PublicKey) error {
	b, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		return err
	}
	return os.WriteFile(path, pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: b}), 0644)
}
