package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/Security-Phoenix-demo/blue-shield-firewall/internal/proxy"
	"github.com/Security-Phoenix-demo/blue-shield-firewall/internal/shim"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Set up phoenix-firewall for the current user (no root required)",
	Long: `Userland setup — no root, no MDM, no code signing required.

What this does:
  1. Creates ~/.config/phoenix-firewall/ with agent.toml
  2. Installs package manager shims to ~/.local/bin/
  3. Adds ~/.local/bin to your shell profile (PATH)
  4. Writes agent-bridge.json for coding agent hooks
  5. Prints next steps for API key setup

Run 'phoenix-firewall enroll --api-key <key>' after this to activate.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		apiKey, _ := cmd.Flags().GetString("api-key")
		apiURL, _ := cmd.Flags().GetString("api-url")
		if apiURL == "" {
			apiURL = "https://phxintel.security"
		}
		return runInit(apiKey, apiURL)
	},
}

func runInit(apiKey, apiURL string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("home dir: %w", err)
	}
	cfgDir := filepath.Join(home, ".config", "phoenix-firewall")
	if err := os.MkdirAll(cfgDir, 0700); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	// Write agent.toml
	tomlPath := filepath.Join(cfgDir, "agent.toml")
	if _, err := os.Stat(tomlPath); os.IsNotExist(err) {
		tomlContent := fmt.Sprintf(`# Phoenix Security Blue Shield - Firewall — agent configuration
# Generated by 'phoenix-firewall init'

api_url = %q
api_key = %q  # replace with your key from phxintel.security
device_id = ""  # endpoint UUID assigned by Phoenix after enrollment
team_id = ""    # optional display/reconciliation hint only; Phoenix authorizes server-side

[policy]
poll_interval_s = 300
stale_threshold_s = 86400

[telemetry]
heartbeat_interval_s = 300
depth = "metadata"

[fail_mode]
# "open" = allow installs when backend unreachable (default for userland)
# "closed" = block installs when backend unreachable (enterprise)
mode = "open"
`, apiURL, apiKey)
		if err := os.WriteFile(tomlPath, []byte(tomlContent), 0600); err != nil {
			return fmt.Errorf("write agent.toml: %w", err)
		}
		fmt.Printf("[phoenix-firewall] created %s\n", tomlPath)
	} else {
		fmt.Printf("[phoenix-firewall] %s already exists, skipping\n", tomlPath)
	}

	// Generate the MITM CA certificate (needed by shims to inject into PM env vars)
	fmt.Println("[phoenix-firewall] generating MITM CA certificate...")
	if _, err := proxy.EnsureCA(cfgDir); err != nil {
		return fmt.Errorf("generate CA: %w", err)
	}
	caPath := filepath.Join(cfgDir, "phoenix-ca.crt")
	fmt.Printf("[phoenix-firewall] CA certificate: %s\n", caPath)

	// Write agent-bridge.json (used by coding agent hooks and shims for local routing)
	bridgePath := filepath.Join(cfgDir, "agent-bridge.json")
	bridge := map[string]interface{}{
		"socket_path":  filepath.Join(cfgDir, "worker.sock"),
		"api_base_url": apiURL,
		"device_id":    "",
		"proxy_port":   8080,
		"ca_path":      caPath,
		"version":      "v4-userland",
		"collector_capabilities": []string{
			"package_manager_shim",
			"developer_software_inventory",
			"package_lockfile_inventory",
			"install_activity_events",
		},
	}
	bridgeBytes, _ := json.MarshalIndent(bridge, "", "  ")
	if err := os.WriteFile(bridgePath, bridgeBytes, 0600); err != nil {
		return fmt.Errorf("write agent-bridge.json: %w", err)
	}
	fmt.Printf("[phoenix-firewall] created %s\n", bridgePath)

	// Install PATH shims
	fmt.Println("[phoenix-firewall] installing package manager shims...")
	if err := shim.InstallPATH(); err != nil {
		return fmt.Errorf("install shims: %w", err)
	}

	fmt.Println()
	fmt.Println("Setup complete. Next steps:")
	if apiKey == "" {
		fmt.Println("  1. Get your API key at https://phxintel.security")
		fmt.Printf("  2. Run: phoenix-firewall enroll --api-key <your-key>\n")
		fmt.Printf("     (or edit %s directly)\n", tomlPath)
	} else {
		fmt.Println("  1. Restart your shell (or source your profile)")
		fmt.Println("  2. Try: npm install lodash  — it will be evaluated by the firewall")
	}
	fmt.Println()
	fmt.Println("Agent hook setup:")
	fmt.Println("  Claude Code : npx @phoenix-security/cli install-hooks claude-code")
	fmt.Println("  Cursor      : add to .cursor/mcp.json (see phxintel.security/docs)")
	return nil
}

func init() {
	initCmd.Flags().String("api-key", "", "Phoenix API key (optional — can be added later via enroll)")
	initCmd.Flags().String("api-url", "https://phxintel.security", "Phoenix API base URL")
	rootCmd.AddCommand(initCmd)
}
